# ====================================
# APPLICATION AND SERVER CONFIGURATION
# ====================================
spring.application.name=e-comerce
server.port=8080
server.error.include-message=always

# ====================================
# DATA BASE CONFIGURATION (POSTGRESQL)
# ====================================
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# =============================
# JPA / HIBERNATE CONFIGURATION
# =============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==================================
# SECURITY SETTINGS (JWT PRE-CONFIG)
# ==================================
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000